/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.locadora.view;

import br.com.locadora.dao.ClienteDAO;
import br.com.locadora.dao.DevolucaoDAO;
import br.com.locadora.dao.ReservaDAO;
import br.com.locadora.model.Cliente;
import br.com.locadora.model.Devolucao;
import br.com.locadora.model.Reserva;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Maria
 */
public class DevolucaoApp extends javax.swing.JFrame {
    private Reserva reserva;
 
    public DevolucaoApp() {
        initComponents();
        init();
    }
    
    private void init(){
        
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        Calendar data = Calendar.getInstance();
        
        dtAtual.setText(dateFormat.format(data.getTime()));
        dtAtual.setEnabled(false);
        carregaComBox();
    }
    
    
    private void carregaComBox(){
        ClienteDAO dao = new ClienteDAO();
        List<Cliente> listaCliente = dao.listaCliente();
        cbxCliente.removeAllItems();
        
        for (Cliente cliente : listaCliente) {
            cbxCliente.addItem(cliente);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbxCliente = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDevolucao = new javax.swing.JTable();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        dtAtual = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cliente: ");

        cbxCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxClienteActionPerformed(evt);
            }
        });

        tbDevolucao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data Retirada", "Data Devolução", "Situação", "Placa", "CPF"
            }
        ));
        jScrollPane1.setViewportView(tbDevolucao);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel3.setText("Data:");

        dtAtual.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        dtAtual.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        dtAtual.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dtAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(btnCancelar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxClienteActionPerformed
        // TODO add your handling code here:
        //System.out.println("click");
        ReservaDAO dao = new ReservaDAO();
        //Reserva rsv = new Reserva();
        try {
            if (cbxCliente.getItemCount() > 1) {
                Cliente cliente = (Cliente) cbxCliente.getSelectedItem();
                List<Reserva> listaReservas = dao.listaCodReserva(cliente.getCpf());
                int listSize = listaReservas.size();
                if(listSize == 0){
                    JOptionPane.showMessageDialog(btnSalvar, "Cliente não possui reservas!");
                    return;
                }
                //System.out.println(listaReservas.toString());
                DefaultTableModel dtmDevolucao = (DefaultTableModel) tbDevolucao.getModel();
                dtmDevolucao.setRowCount(0);
                for (Reserva rsv : listaReservas) {
                    Object[] dados = {rsv.getDataRetirada(), rsv.getDataDevolucao(),
                        rsv.getSituacao(), rsv.getCarro().getModelo(), rsv.getCliente().getCpf()};
                    dtmDevolucao.addRow(dados);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
       
    }//GEN-LAST:event_cbxClienteActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = tbDevolucao.getSelectedRow();
        
        if(linhaSelecionada < 0){
            JOptionPane.showMessageDialog(btnSalvar, "Selecione uma linha!");
             //System.out.println("Selecione uma linha");
             return; 
        }
        
        // obtendo dados da reserva selecionada em cada linha da tabela
        ReservaDAO dao = new ReservaDAO();
        Cliente cliente = (Cliente) cbxCliente.getSelectedItem();
        Reserva rsv = dao.listaCodReserva(cliente.getCpf()).get(linhaSelecionada); 
        
        if(rsv.getSituacao().equals("Concluido")){
            JOptionPane.showMessageDialog(btnSalvar, "Devolução já se encontra concluida!");
            return; 
        }
       
        Devolucao devolucao = new Devolucao();
        devolucao.setCliente(rsv.getCliente());
        devolucao.setCarro(rsv.getCarro());
        /*
        System.out.println(rsv.getCliente().getCpf());
        System.out.println(devolucao.getCarro().getPlaca());
        System.out.println(rsv.getSituacao());
        */
        SwingWorker worker = new SwingWorker<Void, Void>(){

            @Override
            protected Void doInBackground() throws Exception {
                DevolucaoDAO dao = new DevolucaoDAO();
                dao.salvar(devolucao);
                return null;
            }
            
            protected void done(){
                try {
                    get();
                    JOptionPane.showMessageDialog(btnSalvar, "Devolução realizada com sucesso!");
                } catch (InterruptedException | ExecutionException ex) {
                    Logger.getLogger(DevolucaoApp.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        };
        
        worker.execute();
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DevolucaoApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DevolucaoApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DevolucaoApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DevolucaoApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DevolucaoApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cbxCliente;
    private javax.swing.JTextField dtAtual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbDevolucao;
    // End of variables declaration//GEN-END:variables
}
